<?php

namespace App\Exceptions;

use Throwable;

/**
 * Ships captured exceptions back to Makerloft so the AI coding agent can
 * see what's actually breaking in production. Silently no-ops when the
 * MAKERLOFT_ERROR_INGEST_URL / MAKERLOFT_ERROR_INGEST_SECRET env vars
 * aren't set - so local dev, or a deploy where error capture is disabled,
 * stays quiet. A reporter failure never takes down the user's request:
 * everything runs inside a try/catch with a sub-second timeout.
 *
 * Generated by Makerloft at project creation. Safe to edit; if you
 * regenerate the template, your edits stay.
 */
class MakerloftReporter
{
    public static function report(Throwable $exception): void
    {
        try {
            // Short-circuit outside the post-deploy window. DO App Platform
            // does a fresh git clone for every build, so this file's mtime
            // is effectively the container's deploy time. 24 hours matches
            // the server-side gate (config/features.php
            // error_capture_window_hours); if filemtime() fails, we fall
            // through and let the server gate catch stale reports.
            $deployedAt = @filemtime(__FILE__);

            if ($deployedAt !== false && (time() - $deployedAt) > 86400) {
                return;
            }

            // Check all three PHP env sources: CGI/FPM configs may only
            // populate one depending on `variable_order`, and getenv()
            // alone has been seen returning false with vars set via the
            // DO App Platform dashboard.
            $url = self::envVar('MAKERLOFT_ERROR_INGEST_URL');
            $secret = self::envVar('MAKERLOFT_ERROR_INGEST_SECRET');

            if ($url === '' || $secret === '') {
                return;
            }

            $payload = [
                'error_class' => get_class($exception),
                'message' => $exception->getMessage(),
                'file' => $exception->getFile(),
                'line' => $exception->getLine(),
                'stack_trace' => $exception->getTraceAsString(),
                'url' => self::currentUrl(),
                'reported_at' => date('c'),
            ];

            $body = json_encode($payload);

            if ($body === false) {
                return;
            }

            $timestamp = (string) time();
            $signature = hash_hmac('sha256', $timestamp.'.'.$body, $secret);
            $delivery = bin2hex(random_bytes(8));

            $ch = curl_init($url);

            if ($ch === false) {
                return;
            }

            curl_setopt_array($ch, [
                CURLOPT_POST => true,
                CURLOPT_POSTFIELDS => $body,
                CURLOPT_HTTPHEADER => [
                    'Content-Type: application/json',
                    'X-Makerloft-Signature: sha256='.$signature,
                    'X-Makerloft-Timestamp: '.$timestamp,
                    'X-Makerloft-Delivery: '.$delivery,
                ],
                CURLOPT_TIMEOUT => 2,
                CURLOPT_CONNECTTIMEOUT => 1,
                CURLOPT_RETURNTRANSFER => true,
            ]);
            curl_exec($ch);
            curl_close($ch);
        } catch (Throwable) {
            // Never let the reporter break the request.
        }
    }

    private static function currentUrl(): ?string
    {
        if (! isset($_SERVER['REQUEST_URI'])) {
            return null;
        }

        $scheme = (($_SERVER['HTTPS'] ?? 'off') === 'on') ? 'https' : 'http';
        $host = $_SERVER['HTTP_HOST'] ?? ($_SERVER['SERVER_NAME'] ?? 'localhost');

        return $scheme.'://'.$host.$_SERVER['REQUEST_URI'];
    }

    private static function envVar(string $key): string
    {
        $value = $_ENV[$key] ?? $_SERVER[$key] ?? getenv($key);

        return is_string($value) ? $value : '';
    }
}
