<?php

namespace App\Providers;

use App\Exceptions\MakerloftReporter;
use Illuminate\Contracts\Debug\ExceptionHandler;
use Illuminate\Support\ServiceProvider;
use Throwable;

/**
 * Wires MakerloftReporter into Laravel's exception reporting pipeline.
 *
 * Generated by Makerloft at project creation. Register this in
 * bootstrap/providers.php (it's added there automatically; if you
 * remove it, error capture stops).
 */
class MakerloftReporterServiceProvider extends ServiceProvider
{
    public function boot(): void
    {
        $handler = $this->app->make(ExceptionHandler::class);

        // Defensive guard: the ExceptionHandler contract doesn't require
        // reportable(), so we confirm at runtime. PHPStan sees the concrete
        // container binding (which does have it) and flags the check as
        // always-true; ignore just that rule.
        // @phpstan-ignore function.alreadyNarrowedType
        if (! method_exists($handler, 'reportable')) {
            return;
        }

        $handler->reportable(function (Throwable $e): void {
            MakerloftReporter::report($e);
        });
    }
}
